# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SamlAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_name', models.CharField(max_length=255)),
                ('attribute', models.CharField(choices=[('username', 'Alliance Auth Username'), ('email', 'Alliance Auth Email'), ('character_name', 'Main Characters Name'), ('character_id', 'Main Characters ID'), ('corp_name', 'Main Characters Corporation Name'), ('corp_id', 'Main Characters Corporation ID'), ('corp_ticker', 'Main Characters Corporation Ticker'), ('alliance_name', 'Main Characters Alliance Name'), ('alliance_id', 'Main Characters Alliance ID'), ('groups', 'Alliance Auth Groups')], max_length=20)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='allianceauth_idp.AttributeMapping')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name field displayed to users when a login is requested', max_length=50)),
                ('acs_url', models.CharField(help_text='Assertion Consumer Service URL', max_length=255)),
                ('signed', models.BooleanField(default=True, help_text='Cryptographically Sign the SAML Response.')),
                ('x509_cert', models.TextField(blank=True, default='', help_text='The Service Providers X509 certificate from their metadata.')),
                ('require_signed_requests', models.BooleanField(default=True, help_text='Require this Service Provider send only signed SAML requests. You must provide a X509 certificate, otherwise the provided certificate in the request is used, leading to an insecure signature verification whichis effectively the same as setting this value to False.')),
                ('attribute_mapping', models.ForeignKey(default=None, help_text='Attribute mapping to send to this Service Provider with the SAML response.', null=True, on_delete=django.db.models.deletion.CASCADE, to='allianceauth_idp.AttributeMapping')),
                ('groups_can_access', models.ManyToManyField(blank=True, help_text='Groups can access this service provider', to='auth.Group')),
                ('users_can_access', models.ManyToManyField(blank=True, help_text='Users can access this service provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
